name: Collect from Google Drive (every 15 min)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib openpyxl pandas

      # JSON'u dosyaya yaz – heredoc yok, YAML sorunsuz
      - name: Write service account file
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: |
          python -c "import os,sys; open('sa.json','w',encoding='utf-8').write(os.environ['GOOGLE_APPLICATION_CREDENTIALS_JSON']); print('sa.json written')"

      - name: Run collector (Google Drive)
        env:
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
        run: |
          python ci/collector_gdrive_ci.py --folder-id "$DRIVE_FOLDER_ID" --out data/history.csv

      - name: Show CSV (diagnostic)
        run: |
          ls -lah data || true
          [ -f data/history.csv ] && (echo "HEAD of CSV:"; head -n 20 data/history.csv) || echo "CSV not found"

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f data/history.csv
          echo "Staged files:"; git diff --cached --name-only || true
          if ! git diff --cached --quiet; then
            git commit -m "Update history.csv [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
