name: collect

on:
  workflow_dispatch: {}
 # schedule:
    # Her 15 dakikada bir (UTC)
   # - cron: "*/15 * * * *"

permissions:
  contents: write  # commit/push için gerekli

concurrency:
  group: collect
  cancel-in-progress: true

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # diff/commit için geçmiş gerekli

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2 openpyxl

      - name: Run collector (Drive → Scraper Data → data/normalized)
        env:
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          python ci/collector_gdrive_ci.py

      - name: Show normalized files (diagnostic)
        run: |
          echo "---- data/normalized ----"
          ls -lah data/normalized || true

      - name: Commit & push data changes (if any)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A data/normalized

          # Yalnızca değişiklik varsa commit et
          if ! git diff --cached --quiet; then
            git commit -m "Mirror & normalize Drive to data/ [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
